# Generated by Django 4.1.4 on 2023-03-10 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todowoo", "0003_alter_todo_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="datecompleted",
            new_name="completed",
        ),
    ]
